### ISSUE TITLE
无法加载js

### ISSUE THREAD

**Issue by sonicviking** [Julienedies/chrome-extension-contextMenuUtils#1]
提示无法加载stock-list.js，要怎么解决呢

**Comment by Julienedies** [comment]
@sonicviking , 你好,  因为这个插件是自用的, 里面涉及到很多跟我本人电脑相关的环境.
比如 我电脑上跑有 http://localhost:2018/,  http://localhost:3000/ 等server. 所以别人很难使用.  

你为什么会想要用这个呢? 这里面的功能只对我有用. 对别人没用的.

**Comment by sonicviking** [comment]
嗯 其实对插件具体什么用还不太清楚，只是看到对桃县有用，所以想试试，猜测是追踪和自动提取类的。

**Comment by Julienedies** [comment]
@sonicviking , 你也上桃县啊.  我这个插件主要是方便各种操作. 比如浏览桃县的实盘, 股票代码会添加对应的股票名称, 点击股票代码会直接在通达信或同花顺里直接打开. 浏览同花顺网站,可以按股票列表自动浏览. 就是省了一些手工的活 .  
主要是环境配置太复杂, 跟我本机很多东西挂靠在一起.不能单独用,  要不然就让你试试看.
我有个 cli-jhandy的库, 那个倒是从网上抓取数据的, 也能生成通达信的自定义数据格式. 
有兴趣的话, 你可以试试.
话说, 你是从哪看到对桃县有用的?

**Comment by sonicviking** [comment]
我正好是在查有没有什么桃县的插件可以用的，然后就搜索到你这里来了。不能用也没事，毕竟是你自用的。很佩服你们这些技术流啊，另你说的抓数据的，我应该不会弄，我先试试看。
